In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('one-hot-encoding.csv')

In [ ]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [ ]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

# **1. OneHotEncoding using Pandas**

In [ ]:
pd.get_dummies(df,columns=['fuel','owner'])

        brand  km_driven  ...  owner_Test Drive Car  owner_Third Owner
0      Maruti     145500  ...                 False              False
1       Skoda     120000  ...                 False              False
2       Honda     140000  ...                 False               True
3     Hyundai     127000  ...                 False              False
4      Maruti     120000  ...                 False              False
...       ...        ...  ...                   ...                ...
8123  Hyundai     110000  ...                 False              False
8124  Hyundai     119000  ...                 False              False
8125   Maruti     120000  ...                 False              False
8126     Tata      25000  ...                 False              False
8127     Tata      25000  ...                 False              False

[8128 rows x 12 columns]

In [ ]:
df_dummies_int = pd.get_dummies(df, columns=['fuel', 'owner'], dtype=int)
display(df_dummies_int.head())

     brand  km_driven  ...  owner_Test Drive Car  owner_Third Owner
0   Maruti     145500  ...                     0                  0
1    Skoda     120000  ...                     0                  0
2    Honda     140000  ...                     0                  1
3  Hyundai     127000  ...                     0                  0
4   Maruti     120000  ...                     0                  0

[5 rows x 12 columns]

As you can see, by setting `dtype=int`, the new dummy variables are now represented with `0`s and `1`s.

# **2. K-1 OneHotEncoding**

In [ ]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

        brand  km_driven  ...  owner_Test Drive Car  owner_Third Owner
0      Maruti     145500  ...                 False              False
1       Skoda     120000  ...                 False              False
2       Honda     140000  ...                 False               True
3     Hyundai     127000  ...                 False              False
4      Maruti     120000  ...                 False              False
...       ...        ...  ...                   ...                ...
8123  Hyundai     110000  ...                 False              False
8124  Hyundai     119000  ...                 False              False
8125   Maruti     120000  ...                 False              False
8126     Tata      25000  ...                 False              False
8127     Tata      25000  ...                 False              False

[8128 rows x 10 columns]

# **3. OneHotEncoding using SKlearn**

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

The random_state parameter in train_test_split is used for reproducibility. When you set random_state to an integer, it ensures that the data split will be the same every time you run your code. If you don't set random_state, the split will be different each time, which can make it hard to compare results between runs.

In [ ]:
X_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe=OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

drop='first': This parameter is used to prevent multicollinearity, which can be an issue in some machine learning models. When set to 'first', it drops the first category for each feature being encoded. For example, if your 'fuel' column has 'Petrol', 'Diesel', and 'CNG', and 'Petrol' is the first category encountered, then OneHotEncoder will create columns for 'Diesel' and 'CNG' but not 'Petrol'. If both 'Diesel' and 'CNG' are 0, it implicitly means the fuel type is 'Petrol'. This is also known as K-1 encoding.

sparse_output=False: By default, OneHotEncoder returns a sparse matrix, which is efficient for high-dimensional data with many zeros. However, by setting sparse_output=False, you instruct the encoder to return a dense NumPy array instead. This can be more convenient for certain operations or if your dataset is not extremely sparse.

dtype=np.int32: This parameter specifies the data type for the output array. By setting it to np.int32, the encoded values (0s and 1s) will be stored as 32-bit integers. This can help manage memory usage and ensures type consistency if you're integrating with other NumPy operations or machine learning libraries.

In [ ]:
X_train_new=ohe.fit_transform(X_train[['fuel','owner']])

In [ ]:
X_test_new=ohe.transform(X_test[['fuel','owner']])

In [ ]:
X_train_new.shape

(6502, 7)

In [ ]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], dtype=object)

In [ ]:
type(X_train[['brand','km_driven']])

pandas.core.frame.DataFrame

# **4. OneHotEncoding with Top Categories**

In [ ]:
counts=df['brand'].value_counts()
counts

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [ ]:
df['brand'].nunique()

32

In [ ]:
threshold=100
repl=counts[counts <= threshold].index

In [ ]:
pd.get_dummies(df['brand'].replace(repl,'uncoomon'),dtype=np.int32).sample(5)

      BMW  Chevrolet  Ford  Honda  ...  Tata  Toyota  Volkswagen  uncoomon
656     0          0     0      0  ...     0       0           0         0
6255    0          0     0      0  ...     1       0           0         0
2924    0          0     0      0  ...     0       0           0         0
8077    0          0     0      0  ...     0       1           0         0
2992    0          0     0      0  ...     0       0           0         1

[5 rows x 13 columns]

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!git clone https://github.com/Sanket71/Machine-Learning.git

Cloning into 'Machine-Learning'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 36 (delta 8), reused 21 (delta 3), pack-reused 0 (from 0)
Receiving objects: 100% (36/36), 401.58 KiB | 15.45 MiB/s, done.
Resolving deltas: 100% (8/8), done.

In [3]:
%cd Machine-Learning

/content/Machine-Learning

In [4]:
!mkdir -p OneHotEncoding

In [ ]:
!cp "/content/drive/MyDrive/Colab Notebooks/Normalization.ipynb" OneHotEncoding/